### ISSUE TITLE
Test in CI on big-endian arch

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/oxc#11155]
#11119 demonstrated that we have code which relies on the endianness of the system, and that it's not tested in our CI.

There's more code that depends on endianness in our crates, and also in dependencies like [compact_str](https://crates.io/crates/compact_str) (which doesn't have any testing for big endian in its own CI).

Raw transfer currently does not support big endian, only because I'm not sure how to test it.

It would be great if we could add a big endian arch to CI. It'd be ideal if we ran both:

1. `cargo test`
2. `cd napi/parser; pnpm build && pnpm test;`

These probably wouldn't need to run on all PRs, maybe only on main. Tests are quite quick to run, so I doubt would be a big slow-down to CI, unless cross-compilation imposes a large cost.

**Comment by Boshen** [comment]
First attempt: https://github.com/oxc-project/oxc/actions/runs/15132177773/job/42535515689

```
  test-big-endian:
    name: Test Big Endian
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1
      - uses: oxc-project/setup-rust@cd82e1efec7fef815e2c23d296756f31c7cdc03d # v1.0.0
        with:
          save-cache: true # ${{ github.ref_name == 'main' }}
          cache-key: s390x-unknown-linux-gnu
      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
        with:
          platforms: all
          image: tonistiigi/binfmt:qemu-v7.0.0-28
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # v3
        with:
          image: rust:latest
          options: --platform linux/s390x -w ${{ github.workspace }} -v ${{ github.workspace }}:${{ github.workspace }}
          run: |
            export CC=clang
            export CFLAGS="-fuse-ld=lld"
            rustup show
            rustup which cargo
            cargo install cross
            cross test --target s390x-unknown-linux-gnu -p oxc_parser
```

It takes forever to compile inside docker.

Next attempt is to compile outside of docker, and run inside docker.
