### ISSUE TITLE
Configure and check Minimum Supported Rust Version

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc#4874]
https://github.com/oxc-project/oxc/blob/a2269625cc3cef3252c821018536b048deaba037/Cargo.toml#L15

It's 1.74 but seems not enforced?

**Comment by Boshen** [comment]
Do we need some other tool to enforce this?

**Comment by rzvxa** [comment]
AFIK, this value doesn't enforce anything but is more of a convention/suggestion at this point. We have to use third-party solutions in our CI.

https://doc.rust-lang.org/nightly/cargo/guide/continuous-integration.html#verifying-rust-version

**Comment by rzvxa** [comment]
Another option that I can think of would be to set one of our CI test flows to use an older toolchain(matching our msrv).

**Comment by Boshen** [comment]
Thank you for the explanations. I'll play around with this.

**Comment by rzvxa** [comment]
I'm actually working on a PR for it, I was planning to do this in our Windows CI(since it is a standalone step):

```yml
      - name: Install Rust
        working-directory: ${{ env.DEV_DRIVE_WORKSPACE }}
        env:
          CARGO_HOME: ${{ env.DEV_DRIVE }}/.cargo
          RUSTUP_HOME: ${{ env.DEV_DRIVE }}/.rustup
        shell: bash
        run: |
          MSRV=$(awk -F'=' '/rust-version/ {gsub(/[" ]/, "", $2); print $2}' Cargo.toml)
          sed -i -e 's/profile = "default"/profile = "minimal"/g' -e "s/channel = .*/channel = \"$MSRV\"/g" rust-toolchain.toml
          rustup set profile minimal
          rustup show
          git restore .

```
It doesn't require us to use cargo-hack if we only need to check for rust-version compatiblities.
